language: r
sudo: false
cache: packages
r_packages:
  - covr
after_success:
  - Rscript -e 'covr::codecov()'
r_github_packages:
  - mrc-ide/provisionr

addons:
  postgresql: "9.5"
  apt:
    packages:
      - libapparmor-dev
      - libhiredis-dev
      - libpq-dev
      - redis-server

services:
  - postgresql
  - redis-server
